from importlib import import_module
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .backends import (
        Backend,
        RedisBackend,
        RedisBackendError,
        RedisEndpoint,
        RedisLimits,
        RedisProtocolError,
        RedisUnavailable,
        backend,
    )
    from .compat import (
        CompatibilityError,
        Fresh,
        FreshClient,
        FreshRedis,
        FreshZero,
        ServiceFacade,
        xoBenedict,
        xoBranch,
        xoRedis,
    )
    from .rpc import Client, Server, Stream
    from .web import (
        BrowserWrite,
        WebSocketBridge,
        WebSocketLimits,
        WebSocketProtocolError,
        websocket,
    )
from .capabilities import (
    BuildContext,
    Capability,
    CapabilityRuntime,
    CapabilitySpec,
    CommitCoordinator,
    CompiledProfile,
    Normalizer,
    NullCapability,
    Observer,
    Validator,
    compile_profile,
)
from .codec import DEFAULT_CODEC, Codec, CodecLimits, Extension
from .core import EMPTY_RUNTIME, MISSING, XO, CommitPlan, Subscription, XOBuilder
from .events import DerivedEvent, Diagnostics, Event, EventGroup, Operation, Transaction
from .exceptions import (
    AmbiguousRedo,
    AuthenticationError,
    BackpressureError,
    CancelledError,
    CapabilityConflictError,
    CapabilityError,
    CapabilityHandoffError,
    CapabilityLifecycleError,
    CapabilityOrderError,
    ClosedError,
    CodecError,
    CommitOutcomeUnknown,
    ConflictError,
    CrossTreeDependencyError,
    DeadlineExceeded,
    DerivedWriteError,
    FormulaCycleError,
    FormulaError,
    FormulaEvaluationError,
    FormulaMutationError,
    FormulaStaleError,
    HistoryError,
    InvalidPath,
    InvariantViolation,
    MissingPath,
    PersistenceError,
    ProtocolError,
    RecoveryRequired,
    ReentrantMutationError,
    RevisionNotFound,
    StaleNode,
    SubscriberError,
    XOError,
)
from .history import History, Revision, history
from .path import Path, PathLike, parse_path, render_path
from .profiles import Profile
from .projection import Projection, projection
from .service import Service, ServiceNotFound, ServiceRegistry, service
from .validation import Validation, pydantic_validation, validation

_LAZY_EXPORTS = {
    "Backend": ("xo.backends", "Backend"),
    "RedisBackend": ("xo.backends", "RedisBackend"),
    "RedisBackendError": ("xo.backends", "RedisBackendError"),
    "RedisEndpoint": ("xo.backends", "RedisEndpoint"),
    "RedisLimits": ("xo.backends", "RedisLimits"),
    "RedisProtocolError": ("xo.backends", "RedisProtocolError"),
    "RedisUnavailable": ("xo.backends", "RedisUnavailable"),
    "backend": ("xo.backends", "backend"),
    "CompatibilityError": ("xo.compat", "CompatibilityError"),
    "Fresh": ("xo.compat", "Fresh"),
    "FreshClient": ("xo.compat", "FreshClient"),
    "FreshRedis": ("xo.compat", "FreshRedis"),
    "FreshZero": ("xo.compat", "FreshZero"),
    "ServiceFacade": ("xo.compat", "ServiceFacade"),
    "xoBenedict": ("xo.compat", "xoBenedict"),
    "xoBranch": ("xo.compat", "xoBranch"),
    "xoRedis": ("xo.compat", "xoRedis"),
    "Client": ("xo.rpc", "Client"),
    "Server": ("xo.rpc", "Server"),
    "Stream": ("xo.rpc", "Stream"),
    "BrowserWrite": ("xo.web", "BrowserWrite"),
    "WebSocketBridge": ("xo.web", "WebSocketBridge"),
    "WebSocketLimits": ("xo.web", "WebSocketLimits"),
    "WebSocketProtocolError": ("xo.web", "WebSocketProtocolError"),
    "websocket": ("xo.web", "websocket"),
}


def __getattr__(name: str) -> object:
    try:
        module_name, attribute = _LAZY_EXPORTS[name]
    except KeyError as error:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from error
    value = getattr(import_module(module_name), attribute)
    globals()[name] = value
    return value


__all__ = [
    "DEFAULT_CODEC",
    "EMPTY_RUNTIME",
    "MISSING",
    "XO",
    "AmbiguousRedo",
    "AuthenticationError",
    "Backend",
    "BackpressureError",
    "BrowserWrite",
    "BuildContext",
    "CancelledError",
    "Capability",
    "CapabilityConflictError",
    "CapabilityError",
    "CapabilityHandoffError",
    "CapabilityLifecycleError",
    "CapabilityOrderError",
    "CapabilityRuntime",
    "CapabilitySpec",
    "Client",
    "ClosedError",
    "Codec",
    "CodecError",
    "CodecLimits",
    "CommitCoordinator",
    "CommitOutcomeUnknown",
    "CommitPlan",
    "CompatibilityError",
    "CompiledProfile",
    "ConflictError",
    "CrossTreeDependencyError",
    "DeadlineExceeded",
    "DerivedEvent",
    "DerivedWriteError",
    "Diagnostics",
    "Event",
    "EventGroup",
    "Extension",
    "FormulaCycleError",
    "FormulaError",
    "FormulaEvaluationError",
    "FormulaMutationError",
    "FormulaStaleError",
    "Fresh",
    "FreshClient",
    "FreshRedis",
    "FreshZero",
    "History",
    "HistoryError",
    "InvalidPath",
    "InvariantViolation",
    "MissingPath",
    "Normalizer",
    "NullCapability",
    "Observer",
    "Operation",
    "Path",
    "PathLike",
    "PersistenceError",
    "Profile",
    "Projection",
    "ProtocolError",
    "RecoveryRequired",
    "RedisBackend",
    "RedisBackendError",
    "RedisEndpoint",
    "RedisLimits",
    "RedisProtocolError",
    "RedisUnavailable",
    "ReentrantMutationError",
    "Revision",
    "RevisionNotFound",
    "Server",
    "Service",
    "ServiceFacade",
    "ServiceNotFound",
    "ServiceRegistry",
    "StaleNode",
    "Stream",
    "SubscriberError",
    "Subscription",
    "Transaction",
    "Validation",
    "Validator",
    "WebSocketBridge",
    "WebSocketLimits",
    "WebSocketProtocolError",
    "XOBuilder",
    "XOError",
    "backend",
    "compile_profile",
    "history",
    "parse_path",
    "projection",
    "pydantic_validation",
    "render_path",
    "service",
    "validation",
    "websocket",
    "xoBenedict",
    "xoBranch",
    "xoRedis",
]

__version__ = "0.1.0"
