name: Publish JavaScript

on:
  workflow_dispatch:


permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm
      url: https://www.npmjs.com/package/@fire17/xo-state
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun test js/xo.test.js
      - run: bun pm pack --dry-run
      - run: bun publish --access public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
